---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
      Identical code:
        enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
- docs/
